<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Social Graph API
 *
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addAttribute
     *
     * updates (or creates) an attribute.
     *
     */
    public function testAddAttribute()
    {

    }

    /**
     * Test case for delAttribute
     *
     * deletes an attribute.
     *
     */
    public function testDelAttribute()
    {

    }

    /**
     * Test case for delEntity
     *
     * deletes an entity.
     *
     */
    public function testDelEntity()
    {

    }

    /**
     * Test case for getAllEdges
     *
     * retrieves the edges of a node.
     *
     */
    public function testGetAllEdges()
    {

    }

    /**
     * Test case for getAttribute
     *
     * retrieves the value of an entity attribute.
     *
     */
    public function testGetAttribute()
    {

    }

    /**
     * Test case for getAttributes
     *
     * retrieves the existing attribute keys of an entity (edge or node).
     *
     */
    public function testGetAttributes()
    {

    }

    /**
     * Test case for getEdge
     *
     * retrieves an edge.
     *
     */
    public function testGetEdge()
    {

    }

    /**
     * Test case for getEdgeGetters
     *
     * retrieves the edge getter methods of a node.
     *
     */
    public function testGetEdgeGetters()
    {

    }

    /**
     * Test case for getEdgeSetters
     *
     * retrieves the edge setter methods of a node.
     *
     */
    public function testGetEdgeSetters()
    {

    }

    /**
     * Test case for getFounder
     *
     * retrieves the Graph Founder.
     *
     */
    public function testGetFounder()
    {

    }

    /**
     * Test case for getGraph
     *
     * retrieves the main Graph.
     *
     */
    public function testGetGraph()
    {

    }

    /**
     * Test case for getIncomingEdges
     *
     * retrieves the incoming edges of a node.
     *
     */
    public function testGetIncomingEdges()
    {

    }

    /**
     * Test case for getNode
     *
     * retrieves a node.
     *
     */
    public function testGetNode()
    {

    }

    /**
     * Test case for getNodeEdge
     *
     * edge getter.
     *
     */
    public function testGetNodeEdge()
    {

    }

    /**
     * Test case for getOutgoingEdges
     *
     * retrieves the outgoing edges of a node.
     *
     */
    public function testGetOutgoingEdges()
    {

    }

    /**
     * Test case for getSpace
     *
     * retrieves the Space.
     *
     */
    public function testGetSpace()
    {

    }

    /**
     * Test case for getType
     *
     * fetches entity type.
     *
     */
    public function testGetType()
    {

    }

    /**
     * Test case for makeActor
     *
     * creates an Actor object.
     *
     */
    public function testMakeActor()
    {

    }

    /**
     * Test case for makeEdge
     *
     * creates an edge.
     *
     */
    public function testMakeEdge()
    {

    }

    /**
     * Test case for setAttribute
     *
     * updates (or creates) an attribute.
     *
     */
    public function testSetAttribute()
    {

    }

}
